[build-system]
requires = ["setuptools>=61.0"]
build-backend = "setuptools.build_meta"

[tool.setuptools.packages.find]
include = ["internal*", "utils*"]

[project]
name = "gaussian-splatting-lightning"
dynamic = ["version"]
requires-python = ">=3.10"
dependencies = ["opencv-python-headless>=4.11.0.86,<5", "pytorch-lightning>=2.5.5,<3", "lightning[pytorch-extra]>=2.5.5,<3"]

[project.scripts]
gs-fit = "internal.entrypoints.gspl:cli_fit"
gs-val = "internal.entrypoints.gspl:cli_val"
gs-test = "internal.entrypoints.gspl:cli_test"
gs-predict = "internal.entrypoints.gspl:cli_predict"

segany-fit = "internal.entrypoints.seganygs:cli_fit"
segany-val = "internal.entrypoints.seganygs:cli_val"
segany-test = "internal.entrypoints.seganygs:cli_test"
segany-predict = "internal.entrypoints.seganygs:cli_predict"

gs-viewer = "internal.entrypoints.viewer:cli"

[tool.pixi.workspace]
channels = [
    "nvidia",
    "conda-forge",
    "pytorch",
]
platforms = ["linux-64"]

[tool.pixi.dependencies]
cuda-toolkit = { version = "12.4.*", channel = "nvidia" }
pytorch = { version = "2.5.1.*", channel = "pytorch" }
pytorch-cuda = { version = "12.4.*", channel = "pytorch" }
torchvision = { version = "0.20.1.*", channel = "pytorch" }
wandb = ">=0.21.1,<0.22"
viser = ">=0.2.23,<0.3"
matplotlib = ">=3.9.1,<4"
mediapy = ">=1.2.4,<2"
splines = ">=0.3.3,<0.4"
plyfile = ">=1.1,<2"
tensorboard = ">=2.20.0,<3"


[tool.pixi.pypi-dependencies]
gaussian-splatting-lightning = { path = ".", editable = true }
diff_gaussian_rasterization = { git = "https://github.com/graphdeco-inria/diff-gaussian-rasterization.git", rev = "d63efdcd1c644f333fb52cdd494ac0c57ec2a9ca"}
simple-knn = { git = "https://github.com/yzslab/simple-knn.git", rev =  "86710c2d4b46680c02301765dd79e465819c8f19"}

[tool.pixi.tasks]

[tool.pixi.pypi-options]
no-build-isolation = ["diff_gaussian_rasterization", "simple-knn"]
