max_steps: 40000
save_val: true
cache_all_images: true
trainer:
  check_val_every_n_epoch: 10

data:
  val_max_num_images_to_cache: -1
  test_max_num_images_to_cache: -1
  image_uint8: true
  image_on_cpu: false
  parser: 
    class_path: internal.dataparsers.rotated_xray_dataparser.RotatedXRay
    init_args:
      mode: reconstruction
      init_point_cloud_mode: random
model:
  max_save_val_output: 3
  renderer:
    class_path: internal.renderers.deformabel_xray_renderer.CoronaryDeformableXrayRenderer
    init_args:
      deform_network:
        tcnn: false   # if true, tcnn use float16 and may produce nan
      time_encoding:
        n_frequencies: 6
        n_layers: 2
        n_neurons: 256
      optimization:
        enable_ast: true
      reverse_gray_scale: true    # DSA image usually has reverse gray scale
  metric:
    class_path: internal.metrics.rotate_xray_metrics.RotateXrayMetrics
  gaussian:
    class_path: internal.models.xray_coronary_gaussian.XrayCoronaryGaussian
  density:
    class_path: internal.density_controllers.rotate_xray_density_controller.RotateXrayDensityController
  renderer_output_types: 
    - gray_image_coronary
    - gray_image_background
    - gray_image_whole
  saver:
    class_path: internal.savers.x_ray_saver.XRaySaver
    init_args:
      save_states: 
      - coronary
  