max_steps: 40000
save_val: true
cache_all_images: true
trainer:
  check_val_every_n_epoch: 10
data:
  val_max_num_images_to_cache: -1
  test_max_num_images_to_cache: -1
  image_uint8: true
  parser: 
    class_path: internal.dataparsers.xray_dataparser.parser.XRayDataParser
    init_args:
      meta_loader:
        class_path: internal.dataparsers.xray_dataparser.meta.XRayMetaLoader
      cloud_parser:
        class_path: internal.dataparsers.xray_dataparser.cloud_parsers.UniformCloudParser
        init_args:
          num_points: 100_000
      spliter:
        class_path: internal.dataparsers.xray_dataparser.splitters.ReconstructionSpliter
      cameras_builder:
        class_path: internal.dataparsers.xray_dataparser.cameras_builder.RotateXRayCamerasBuilder
      dataset_builder:
        class_path: internal.dataparsers.xray_dataparser.datasets.ImagesDatasetBuilder
        init_args:
          dataset_config:
            class_path: internal.dataparsers.xray_dataparser.datasets.ImagesDatasetConfig
            init_args:
              image_uint8: true
model:
  # max_save_val_output: 50
  renderer:
    class_path: internal.renderers.deformable_renderer.DeformableRenderer
    init_args:
      deform_network:
        tcnn: false
        rotate_xyz: true
      time_encoding:
        n_frequencies: 6
        n_layers: 2
        n_neurons: 256
      optimization:
        enable_ast: false