max_steps: 10000
save_val: false
cache_all_images: true
trainer:
  check_val_every_n_epoch: 10
  precision: 16-mixed
  callbacks:
    - class_path: internal.callbacks.scene_saver.SceneSaver
      init_args:
        save_iterations: [10000]
        saver:
          class_path: internal.savers.x_ray_saver.XRaySaver
          init_args:
            save_ckpt: true
            save_ply: true
            save_nii: true
            save_phase: 0.
    - class_path: internal.callbacks.callbacks.ValidateOnTrainEnd
    - class_path: internal.callbacks.callbacks.KeepRunningIfWebViewerEnabled
    - class_path: internal.callbacks.save_image.SaveImage
      init_args:
        save_val_output: true
        max_save_val_output: -1
        max_image_saving_threads: 16
    - class_path: internal.callbacks.callbacks.ProgressBar
    - class_path: internal.callbacks.callbacks.StopDataLoaderCacheThread
data:
  parser: 
    class_path: internal.dataparsers.xray_dataparser.parser.XRayDataParser
    init_args:
      meta_loader:
        class_path: internal.dataparsers.xray_dataparser.meta.XRayMetaLoader
      cloud_parser:
        class_path: internal.dataparsers.xray_dataparser.cloud_parsers.RandomCloudParser
        init_args:
          num_points: 100_000
      spliter:
        class_path: internal.dataparsers.xray_dataparser.splitters.RenderNewViewsSpliter
        init_args:
          train_ratio: 0.8
      cameras_builder:
        class_path: internal.dataparsers.xray_dataparser.cameras_builder.RotateXRayCamerasBuilder
      dataset_builder:
        class_path: internal.dataparsers.xray_dataparser.datasets.ImagesDatasetBuilder
        init_args:
          dataset_config:
            class_path: internal.dataparsers.xray_dataparser.datasets.ImagesDatasetConfig
            init_args:
              image_uint8: true
      init_point_cloud_num: 100_000
      train_ratio: 0.8
model:
  renderer:
    class_path: internal.renderers.xray_renderer.XrayRenderer
    init_args:
      optimization_config:
        enable_ast: true
        log_gradients: true
        grad_log_interval: 50
  metric:
    class_path: internal.metrics.rotate_xray_metrics.RotateXrayMetrics
  gaussian:
    class_path: internal.models.xray_coronary_gaussian.XrayCoronaryGaussian
    init_args:
      optimization:
        log_gradients: true
        grad_log_interval: 50
  density:
    class_path: internal.density_controllers.rotate_xray_density_controller.RotateXrayDensityController
  renderer_output_types: 
    - gray_image
    - gray_coronary
  saver:
    class_path: internal.savers.x_ray_saver.XRaySaver
    init_args:
      save_ckpt: false
      save_ply: false
      save_nii: true
      save_phase: 0.5