max_steps: 20000
save_val: true
cache_all_images: true
trainer:
  check_val_every_n_epoch: 7
  precision: 16-mixed

save_iterations: [5000, 10000, 20000]


data:
  val_max_num_images_to_cache: -1
  test_max_num_images_to_cache: -1
  image_uint8: true
  image_on_cpu: false
  parser: 
    class_path: internal.dataparsers.rotated_xray_dataparser.RotatedXRay
    init_args:
      mode: render-new-views
      init_point_cloud_mode: random
      init_point_cloud_num: 100_000
      train_ratio: 0.5
      random_loader_mode: random-start
model:
  max_save_val_output: 2
  renderer:
    class_path: internal.renderers.deformabel_xray_renderer.CoronaryDeformableXrayRenderer
    init_args:
      optimization_config:
        enable_ast: true
        log_gradients: true
        grad_log_interval: 50
      deform_model_config:
        class_path: internal.deform_models.HashGridDeformConfig
        init_args:
          x_multires: 13
          log2_hashmap_size: 19
          max_resolution: 2048
  metric:
    class_path: internal.metrics.rotate_xray_metrics.RotateXrayMetrics
    init_args:
      fused_ssim: true
      w_phase_aware_loss: 0.
      w_base_train_loss: 1.0
      enable_frangi_loss: false
      w_frangi_loss: 0.0
      enable_deform_tv_loss: false
      w_deform_tv_loss: 0.0
      deform_tv_num_patches: 1
      deform_tv_patch_grid_size: 8
      deform_tv_patch_extent_ratio: 0.2
      deform_tv_norm: l1
      deform_tv_eps: 1.0e-6
  gaussian:
    class_path: internal.models.xray_coronary_gaussian.XrayCoronaryGaussian
    init_args:
      optimization:
        log_gradients: true
        grad_log_interval: 50
  density:
    class_path: internal.density_controllers.rotate_xray_density_controller.RotateXrayDensityController
  renderer_output_types: 
    - gray_image
    - gray_coronary
  saver:
    class_path: internal.savers.x_ray_saver.XRaySaver
    init_args:
      save_ckpt: false
      save_ply: false
      save_nii: true
      save_phase: 0.5