max_steps: 40000
save_val: true
cache_all_images: true
trainer:
  check_val_every_n_epoch: 10
data:
  val_max_num_images_to_cache: -1
  test_max_num_images_to_cache: -1
  image_uint8: true
  parser: 
    class_path: internal.dataparsers.rotated_xray_dataparser.RotatedXRay
    init_args:
      mode: reconstruction
      init_point_cloud_mode: uniform
model:
  # max_save_val_output: 50
  renderer:
    class_path: internal.renderers.deformable_renderer.DeformableRenderer
    init_args:
      deform_network:
        tcnn: false
        rotate_xyz: true
      time_encoding:
        n_frequencies: 6
        n_layers: 2
        n_neurons: 256
      optimization:
        enable_ast: false