max_steps: 40000
save_val: true
cache_all_images: true
trainer:
  check_val_every_n_epoch: 10
  callbacks:
    - class_path: internal.callbacks.scene_saver.SceneSaver
    - class_path: internal.callbacks.callbacks.ValidateOnTrainEnd
    - class_path: internal.callbacks.callbacks.KeepRunningIfWebViewerEnabled
    - class_path: internal.callbacks.save_image.SaveImage
      init_args:
        save_val_output: true
        max_save_val_output: -1
        max_image_saving_threads: 16
    - class_path: internal.callbacks.callbacks.ProgressBar
    - class_path: internal.callbacks.callbacks.StopDataLoaderCacheThread
data:
  val_max_num_images_to_cache: -1
  test_max_num_images_to_cache: -1
  image_uint8: true
  image_on_cpu: false
  parser: 
    class_path: internal.dataparsers.rotated_xray_dataparser.RotatedXRay
    init_args:
      mode: reconstruction
      init_point_cloud_mode: central-line
model:
  renderer:
    class_path: internal.renderers.deformabel_xray_renderer.CoronaryDeformableXrayRenderer
    init_args:
      deform_network:
        tcnn: true
      time_encoding:
        n_frequencies: 6
        n_layers: 2
        n_neurons: 256
      optimization:
        enable_ast: true
      reverse_gray_scale: true    # DSA image usually has reverse gray scale
  metric:
    class_path: internal.metrics.rotate_xray_metrics.RotateXrayMetrics
    init_args:
      enable_deform_tv_loss: false
      w_deform_tv_loss: 0.0
      deform_tv_num_patches: 1
      deform_tv_patch_grid_size: 8
      deform_tv_patch_extent_ratio: 0.2
      deform_tv_norm: l1
      deform_tv_eps: 1.0e-6
  gaussian:
    class_path: internal.models.xray_coronary_gaussian.XrayCoronaryGaussian
  density:
    class_path: internal.density_controllers.rotate_xray_density_controller.RotateXrayDensityController
    init_args:
      absgrad: true
  renderer_output_types: 
    - gray_image_coronary
    - gray_image_whole