# gaussian model 中增加用傅里叶级数形式记录的密度变化频率分量，渲染时用使用频率分量生成随时间变化密度
project: RotCA-GR

max_steps: 20000

trainer:
  log_every_n_steps: 500
  check_val_every_n_epoch: 50
  precision: 16-mixed
  callbacks:
    - class_path: internal.callbacks.callbacks.ValidateOnTrainEnd
    - class_path: internal.callbacks.callbacks.ProgressBar
      init_args:
        refresh_rate: 50
    
    - class_path: internal.callbacks.scene_saver.SceneSaver
      init_args:
        save_iterations: [20000]
        saver:
          class_path: internal.savers.xray_4d_saver.XRaySaver
          init_args:
            save_ckpt: false
            save_vtp: false
            save_volume: false
            save_label_threshold: 0.0344
            save_time_or_type: 0.5
            save_phase: 0.
    
    # - class_path: internal.callbacks.callbacks.KeepRunningIfWebViewerEnabled

    - class_path: internal.callbacks.save_image.SaveImage
      init_args:
        save_val_output: true
        max_save_val_output: 20
        max_image_saving_threads: 3


data:
  parser: 
    class_path: internal.dataparsers.xray_dataparser.parser.XRayDataParserBuilder
    init_args:
      meta_loader:
        class_path: internal.dataparsers.xray_dataparser.meta.XRayMetaLoader
      cloud_parser:
        class_path: internal.dataparsers.xray_dataparser.cloud_parsers.RandomCloudParser
        init_args:
          num_points: 10_000
      spliter:
        class_path: internal.dataparsers.xray_dataparser.splitters.UniformIntervalSpliter
        init_args:
          train_ratio: 0.8
      cameras_builder:
        class_path: internal.dataparsers.xray_dataparser.cameras_builder.RotateXRayCamerasBuilder
      dataset_builder:
        class_path: internal.dataparsers.xray_dataparser.datasets.ImagesDatasetBuilder
        init_args:
          dataset_config:
            image_uint8: false

model:
  renderer:
    class_path: internal.renderers.xray_4d_renderer.Xray4DRender
    init_args:
      optimization_config:
        enable_ast: true
      deform_model_config:
        class_path: internal.deform_models.HashGridDeformConfig
        init_args:
          x_multires: 13
          log2_hashmap_size: 19
          max_resolution: 2048
  metric:
    class_path: internal.metrics.Xray4DMetrics
    init_args:
      fused_ssim: true
      w_gray_loss: 1.0
      w_ssim_loss: 1.0
      w_density_var: 0.0
      w_xyz_var: 0.0
  gaussian:
    class_path: internal.models.xray_4d_gaussian.Xray4DGaussian
    init_args:
      optimization:
        density_freq_res_max: 5
  density:
    class_path: internal.density_controllers.xray_4d_density_controller.Xray4DDensityController