# 对有造影剂流动的数据使用原始的只考虑冠脉形变的模型，作为基线
max_steps: 20000
save_val: true
cache_all_images: true
trainer:
  check_val_every_n_epoch: 5
  precision: 16-mixed

save_iterations: [20000]

data:
  val_max: null   # 3000
  image_on_cpu: false
  parser:
    class_path: internal.dataparsers.TiffDataParserConfig
    init_args:
      mode: render-new-views
      init_point_cloud_mode: random
      init_point_cloud_num: 100_000
      train_ratio: 0.8
      base_name: rotate_dsa

model:
  max_save_val_output: 10
  renderer:
    class_path: internal.renderers.deformabel_xray_renderer.CoronaryDeformableXrayRenderer
    init_args:
      optimization_config:
        enable_ast: true
        log_gradients: true
        grad_log_interval: 50
      deform_model_config:
        class_path: internal.deform_models.HashGridDeformConfig
        init_args:
          x_multires: 13
          log2_hashmap_size: 19
          max_resolution: 2048
  metric:
    class_path: internal.metrics.rotate_xray_metrics.RotateXrayMetrics
    init_args:
      fused_ssim: true
      w_gray_loss: 1.0
      w_ssim_loss: 1.0
  gaussian:
    class_path: internal.models.xray_coronary_gaussian.XrayCoronaryGaussian
    init_args:
      optimization:
        log_gradients: true
        grad_log_interval: 50
  density:
    class_path: internal.density_controllers.rotate_xray_density_controller.RotateXrayDensityController
  renderer_output_types: 
    - gray_image
    - gray_coronary
  saver:
    class_path: internal.savers.x_ray_saver.XRaySaver
    init_args:
      save_ckpt: false
      save_ply: false
      save_nii: true
      save_phase: 0.5